apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: swe304
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: post
