apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32140
      protocol: TCP
  type: NodePort