apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: mkilci2/app:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB
              value: swe304
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: post

